sudo: required
services:
  - docker

before_install:
  - docker build -t loserforever/docker-react -f Dockerfile.dev .

script:
  - docker run loserforever/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  name: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-149101267308"
  bucket_path: "docker-react"
  on:
    branch: main
  access-key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
